name: CI/CD Pipeline
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
 
    - name: Install dependencies
      run: npm install
 
    - name: Run tests
      run: npm test
 
    - name: Build Docker images
      run: |
        docker build -t 2020wa86953/avanta_retail/order-service:latest -f order-service/Dockerfile order-service
        docker build -t 2020wa86953/avanta_retail/payment-service:latest -f payment-service/Dockerfile payment-service
 
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
 
    - name: Push Docker images
      run: |
        docker push 2020wa86953/avanta_retail/order-service:latest
        docker push 2020wa86953/avanta_retail/payment-service:latest
 
    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v2
      with:
        manifests: |
          k8s/order-deployment.yaml
          k8s/payment-deployment.yaml
          k8s/order-service.yaml
          k8s/payment-service.yaml
        images: |
          2020wa86953/avanta_retail/order-service:latest
          2020wa86953/avanta_retail/payment-service:latest

