version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: avanta_retail
    ports:
      - "3306:3306"
 
  order-service:
    build: ./order-service
    ports:
      - "3000:3000"
    depends_on:
      - mysql
 
  payment-service:
    build: ./payment-service
    ports:
      - "3001:3001"
    depends_on:
      - MySQL

